Traceback (most recent call last):
  File "listify_length_k47.py", line 4, in <module>
    listify_length.optimize_list_len(47)
  File "/scratch/groups/aetkin/ebeam/neuro-knowledge-engine/ontology/logistic_regression/sherlock/listify_length.py", line 86, in optimize_list_len
    lists, circuits = load_raw_domains(k)
  File "/scratch/groups/aetkin/ebeam/neuro-knowledge-engine/ontology/logistic_regression/sherlock/listify_length.py", line 37, in load_raw_domains
    lists = pd.read_csv(list_file, index_col=None)
  File "/home/users/ebeam/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/users/ebeam/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/users/ebeam/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/users/ebeam/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/users/ebeam/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'../../lists/lists_k47.csv' does not exist: b'../../lists/lists_k47.csv'
srun: error: sh02-02n10: task 0: Exited with exit code 1
srun: Terminating job step 66032343.0
