Traceback (most recent call last):
  File "data-driven_forward.py", line 4, in <module>
    prediction.train_classifier.run('data-driven', 'forward', suffix='')
AttributeError: 'function' object has no attribute 'run'
srun: error: sh-101-42: task 0: Exited with exit code 1
