Traceback (most recent call last):
  File "data-driven_reverse.py", line 4, in <module>
    prediction.train_classifier.run('data-driven', 'reverse', suffix='')
AttributeError: 'function' object has no attribute 'run'
srun: error: sh-101-36: task 0: Exited with exit code 1
